spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-rain-dev
---
spring:
  profiles: test
  application:
  name: microservicecloud-config-rain-test