spring:
  profiles:
  active:
  - dev

---

server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.gjt.mm.mysql.Driver
  url: jdbc:mysql://localhost:3306/db01
  username: root
  password: root
  dbcp2:
     min-idle: 5                                         
     initial-size: 5                                   
     max-total: 5             
     max-wait-millis: 200

mybatis:
  type-aliases-package: com.rain.cloud.bean
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

eureka:
  client: 
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      #defaultZone: http://10.2.3.3:8000/eureka
  instance:
    instance-id:dept-8001.com
    prefer-ip-address: true

info:
  app.name: ssm-microservicecloud
  company.name: www.baidu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
